services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: market-artha-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_artha_dev
    ports:
      - "5433:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Enables persistence across restarts
    # For local dev, persistence is optional; no password by default
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: backend.dev.Dockerfile
    env_file:
      - ./.env
    working_dir: /app/apps/backend
    command: sh -c "corepack enable pnpm && pnpm --filter backend --filter shared install && nohup pnpm --filter shared build:watch > /tmp/shared-watch.log 2>&1 & sleep 2 && pnpm exec prisma migrate deploy --schema=prisma/schema.prisma && pnpm exec prisma generate --schema=prisma/schema.prisma && pnpm start:debug"
    container_name: market-artha-backend-dev
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    restart: unless-stopped

  frontend:
    image: node:24-slim
    env_file:
      - ./.env
    working_dir: /app
    command: sh -c "corepack enable pnpm && pnpm --filter frontend --filter shared install && pnpm --filter frontend dev"
    container_name: market-artha-frontend-dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data_dev:
  redis-data:
    driver: local
